version: "3.8"

services:

  db_pokemon:
    image: postgres:11.13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pokemon
      - POSTGRES_DB=pokemon
      - POSTGRES_USER=pokemon
    networks:
      - pokemon_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  db_airflow:
    image: postgres:11.13-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
    networks:
      - pokemon_network

  pokemon_mq:
    image: rabbitmq:3-management-alpine
    ports:
      - 8081:8080
      - 5672:5672
      - 15672:15672
    networks:
      - pokemon_network

  airflow:
    image: apache/airflow:1.10.15-python3.8
    ports:
      - 8080:8080
      - 8888:8888
    environment:
      - AIRFLOW_CONN_POKEMON_DB=postgresql+psycopg2://pokemon:pokemon@db_pokemon:5432/pokemon
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db_airflow:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__CELERY__CELERY_APP_NAME=airflow.executors.celery_executor
      - AIRFLOW__CELERY__BROKER_URL=pyamqp://guest:guest@pokemon_mq:5672/
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@db_airflow:5432/airflow
      - AIRFLOW__CELERY__DEFAULT_QUEUE=celery
      - AIRFLOW__CELERY__FLOWER_URL_PREFIX=/flower
    networks:
      - pokemon_network
    volumes:
      - ./dags/:/opt/airflow/dags/
    entrypoint: /bin/bash
    depends_on:
      - db_pokemon
      - db_airflow
      - pokemon_mq
    links:
      - "db_pokemon:db_pokemon"
      - "db_airflow:db_airflow"
    command: -c '(airflow db init && airflow users create --username admin --password admin --role Admin --firstname Anonymous --lastname Admin --email admin@example.org); airflow webserver & airflow scheduler & airflow worker & airflow flower --broker=amqp://guest:guest@pokemon_mq:5672/ --port=8888'

networks:
  pokemon_network:
    driver: bridge